[custom.all.sqlite3]
type   = "local"
path   = "."
ipkg   = "sqlite3.ipkg"
test   = "test/test.ipkg"

[custom.all.sqlite3-rio]
type   = "local"
path   = "sqlite3-rio"
ipkg   = "sqlite3-rio.ipkg"

[custom.all.bytestring]
type   = "git"
url    = "https://github.com/stefan-hoeck/idris2-bytestring"
commit = "latest:main"
ipkg   = "bytestring.ipkg"
