[custom.all.sqlite3]
type   = "local"
path   = "."
ipkg   = "sqlite3.ipkg"
test   = "test/test.ipkg"

[custom.all.sqlite3-rio]
type   = "local"
path   = "sqlite3-rio"
ipkg   = "sqlite3-rio.ipkg"

[custom.all.sqlite3-docs]
type   = "local"
path   = "docs"
ipkg   = "docs.ipkg"

[custom.all.quantifiers-extra]
type   = "git"
url    = "https://github.com/stefan-hoeck/idris2-quantifiers-extra"
commit = "latest:main"
ipkg   = "quantifiers-extra.ipkg"
